# Generated by Django 5.2.6 on 2026-01-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('stage_type', models.CharField(choices=[('ON_STAGE', 'On Stage'), ('OFF_STAGE', 'Off Stage')], max_length=10)),
                ('event_type', models.CharField(choices=[('SINGLE', 'Single'), ('GROUP', 'Group')], max_length=10)),
                ('min_team_size', models.PositiveIntegerField(default=1)),
                ('max_team_size', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.team')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('event', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=150)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='app.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='app.team')),
            ],
            options={
                'unique_together': {('event', 'team', 'participant_name')},
            },
        ),
    ]
